export const headingIconText = {
    // map__IconTxt: "Service Areas",
    // projectUs__IconTxt: "Star Project with us",
    // ourServices__IconTxt: "Services",
    // bestServices__IconTxt: "Best Service Company",
    // ourExperience__IconTxt: "Our Experience in Contractors",
    // quality__IconTxt: "Quality of Our Company",
    // trustUs__IconTxt: "Why You Trust Us",
    // GeneralContractors__IconTxt: "The Leading Contractors Company",
    // services__IconTxt: "Services",
    reviews__IconTxt: "Reviews",
    gallery__IconTxt: "Gallery",
    chooseUs__IconTxt: "Chooses Us",
    faq__IconTxt: "FAQ",
    aboutUs__IconTxt: "About Us",
    installationCompany__IconTxt: "Installation Company",
    repairCompany__IconTxt: "Repair Company",
    projectDesigns__IconTxt: "Project Through Designs",
    exteriorContractors__IconTxt: "Exterior Contractors",
    experienced__IconTxt: "Experienced",
    professional__IconTxt: "Professional",
    bestStuccoPainting__IconTxt: "Best Stucco Painting",
    workWithUs__IconTxt: "Work With us",
    workingProcess__IconTxt: "Process",
    readyToWork__IconTxt: "Ready to Work with us",
    // costBudgeting__IconTxt: "Cost & Budgeting",
    // factorsToHiringUs__IconTxt: "Factors to Hiring Us",
    
}